name: Docker

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: bluewalk/openthermgateway2mqtt:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
